services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: gophermart
      POSTGRES_PASSWORD: gophermart
      POSTGRES_DB: gophermart
    ports:
      - "5432:5432"
    volumes:
      - gophermart-pgdata:/var/lib/postgresql/data

volumes:
  gophermart-pgdata:
